import {
    BatchGetItemCommand,
    BatchWriteItemCommand,
    ConditionalCheckFailedException,
    CreateTableCommand,
    DeleteItemCommand,
    DeleteTableCommand,
    DescribeTableCommand,
    DynamoDBClient,
    DynamoDBServiceException,
    GetItemCommand,
    ListTablesCommand,
    PutItemCommand,
    QueryCommand,
    ResourceNotFoundException,
    ScanCommand,
    TransactionCanceledException,
    TransactWriteItemsCommand,
    UpdateItemCommand
} from '@aws-sdk/client-dynamodb';
import type {
    AttributeValue,
    ConditionCheck,
    CreateTableCommandInput,
    DeleteItemCommandInput,
    KeySchemaElement,
    PutItemCommandInput,
    QueryCommandInput,
    ScanCommandInput,
    TableDescription,
    TransactWriteItemsCommandInput,
    UpdateItemCommandInput
} from '@aws-sdk/client-dynamodb';
import {QuerySerializer} from './query-serializer';
import {QueryTableAdmin} from './query-table-admin';
import type {DynamoDBTableDefinition} from './query-table-admin';
import {ValueUtils} from './value-utils';

// The memory backend executes SDK command objects directly, so query code can
// be tested without a running DynamoDB service.
type Document = Record<string, unknown>;
type AttributeMap = Record<string, AttributeValue>;
type WriteInput = Pick<PutItemCommandInput, 'TableName'>
    & Partial<PutItemCommandInput & UpdateItemCommandInput & DeleteItemCommandInput>;
type InitialTables = readonly (DynamoDBTableDefinition | CreateTableCommandInput)[];
type MemoryCommand =
    | CreateTableCommand
    | DeleteTableCommand
    | DescribeTableCommand
    | ListTablesCommand
    | PutItemCommand
    | GetItemCommand
    | UpdateItemCommand
    | DeleteItemCommand
    | QueryCommand
    | ScanCommand
    | BatchGetItemCommand
    | BatchWriteItemCommand
    | TransactWriteItemsCommand;

interface MemoryTable {
    description: TableDescription;
    items: Map<string, Document>;
}

interface MemorySnapshot {
    version: 1;
    tables: Array<{
        description: TableDescription;
        items: AttributeMap[];
    }>;
}

interface MemoryPersistence {
    load(): Promise<MemorySnapshot | undefined>;
    save(snapshot: MemorySnapshot): Promise<void>;
    close?(): Promise<void>;
}

function validation(message: string): never {
    throw new DynamoDBServiceException({
        name: 'ValidationException',
        message: message,
        $fault: 'client',
        $metadata: {}
    });
}

function compare(left: unknown, right: unknown): number | null {
    if (typeof left === 'number' && typeof right === 'number') {
        return left - right;
    }
    if (typeof left === 'string' && typeof right === 'string') {
        return left < right ? -1 : left > right ? 1 : 0;
    }
    if (left instanceof Uint8Array && right instanceof Uint8Array) {
        const length = Math.min(left.length, right.length);
        for (let index = 0; index < length; index++) {
            if (left[index] !== right[index]) {
                return left[index] - right[index];
            }
        }
        return left.length - right.length;
    }
    return null;
}

/** Evaluates the expression subset generated by QueryBuilder. */
class MemoryExpression {
    private position = 0;
    private tokens: string[];

    constructor(
        private expression: string,
        private item: Document,
        private names: Record<string, string>,
        private values: AttributeMap
    ) {
        this.tokens = expression.match(/#[\w.-]+|:[\w.-]+|<>|<=|>=|[=<>(),]|[A-Za-z_]+/g) || [];
        if (this.tokens.join('') !== expression.replace(/\s/g, '')) {
            validation(`Unsupported in-memory expression: ${expression}`);
        }
    }

    evaluate(): boolean {
        const result = this.conjunction();
        if (this.position !== this.tokens.length) {
            validation(`Unsupported in-memory expression: ${this.expression}`);
        }
        return result;
    }

    private take(expected?: string): string {
        const token = this.tokens[this.position++];
        if (token === undefined || (expected !== undefined && token !== expected)) {
            validation(`Invalid in-memory expression: ${this.expression}`);
        }
        return token;
    }

    private conjunction(): boolean {
        let result = this.predicate();
        while (this.tokens[this.position] === 'AND') {
            this.take('AND');
            const next = this.predicate();
            result = result && next;
        }
        return result;
    }

    private operand(): unknown {
        const token = this.take();
        if (token.startsWith('#') && Object.prototype.hasOwnProperty.call(this.names, token)) {
            const name = this.names[token];
            return Object.prototype.hasOwnProperty.call(this.item, name)
                ? this.item[name]
                : undefined;
        }
        if (token.startsWith(':') && Object.prototype.hasOwnProperty.call(this.values, token)) {
            return QuerySerializer.parseField(this.values[token]);
        }
        return validation(`Unknown in-memory expression operand: ${token}`);
    }

    private predicate(): boolean {
        const token = this.tokens[this.position];
        if (token === 'NOT') {
            this.take();
            return !this.predicate();
        }
        if (token === '(') {
            this.take();
            const result = this.conjunction();
            this.take(')');
            return result;
        }
        if (['attribute_exists', 'attribute_not_exists', 'contains', 'begins_with'].includes(token)) {
            this.take();
            this.take('(');
            const left = this.operand();
            if (token === 'attribute_exists' || token === 'attribute_not_exists') {
                this.take(')');
                return token === 'attribute_exists'
                    ? left !== undefined
                    : left === undefined;
            }
            this.take(',');
            const right = this.operand();
            this.take(')');
            if (typeof left === 'string' && typeof right === 'string') {
                return token === 'contains' ? left.includes(right) : left.startsWith(right);
            }
            if (token === 'begins_with' && left instanceof Uint8Array && right instanceof Uint8Array) {
                return ValueUtils.equals(left.subarray(0, right.length), right);
            }
            return token === 'contains'
                && (Array.isArray(left) || left instanceof Set)
                && Array.from(left).some((entry) => ValueUtils.equals(entry, right));
        }
        const left = this.operand();
        const operator = this.take();
        if (operator === 'IN') {
            this.take('(');
            const candidates = [this.operand()];
            while (this.tokens[this.position] === ',') {
                this.take();
                candidates.push(this.operand());
            }
            this.take(')');
            return left !== undefined && candidates.some((candidate) => ValueUtils.equals(left, candidate));
        }
        const right = this.operand();
        const order = compare(left, right);
        if (operator === 'BETWEEN') {
            this.take('AND');
            const upperOrder = compare(left, this.operand());
            return order !== null && upperOrder !== null && order >= 0 && upperOrder <= 0;
        }
        switch (operator) {
            case '=': return left !== undefined && ValueUtils.equals(left, right);
            case '<>': return left !== undefined && !ValueUtils.equals(left, right);
            case '<': return order !== null && order < 0;
            case '<=': return order !== null && order <= 0;
            case '>': return order !== null && order > 0;
            case '>=': return order !== null && order >= 0;
            default: return validation(`Unsupported in-memory operator: ${operator}`);
        }
    }
}

/** In-memory implementation of the DynamoDB operations used by QueryBuilder. */
class InMemoryDynamoDB {
    /** DynamoDB-compatible client passed to QueryBuilder and typed tables. */
    readonly db: DynamoDBClient;
    private tables = new Map<string, MemoryTable>();
    private tokens = new Map<string, {input: TransactWriteItemsCommandInput; expires: number}>();
    private closed = false;
    private operation: Promise<void> = Promise.resolve();
    private readonly ready: Promise<void>;

    /** Creates an isolated in-memory backend and optionally seeds its table definitions. */
    constructor(tables: InitialTables = [], private readonly persistence?: MemoryPersistence) {
        this.db = new DynamoDBClient({
            region: 'us-east-1',
            credentials: {accessKeyId: 'in-memory', secretAccessKey: 'in-memory'}
        });
        this.db.send = (async (command: MemoryCommand) => {
            return this.enqueue(async () => {
                await this.ready;
                if (this.closed) {
                    throw new Error('In-memory DynamoDB backend is closed');
                }
                const response = this.execute(command);
                if (this.mutates(command)) {
                    await this.persistence?.save(this.snapshot());
                }
                return ValueUtils.clone(response);
            });
        }) as typeof this.db.send;
        for (const table of tables) {
            this.execute(new CreateTableCommand('name' in table ? QueryTableAdmin.toCreateTableInput(table) : table));
        }
        this.ready = this.load();
    }

    /** Removes all records and transaction tokens while retaining table definitions. */
    async reset(): Promise<void> {
        await this.enqueue(async () => {
            await this.ready;
            if (this.closed) {
                throw new Error('In-memory DynamoDB backend is closed');
            }
            for (const table of this.tables.values()) table.items.clear();
            this.tokens.clear();
            await this.persistence?.save(this.snapshot());
        });
    }

    /** Closes the client, removes table definitions, and rejects future requests. */
    async close(): Promise<void> {
        if (this.closed) {
            return;
        }
        this.closed = true;
        await this.ready;
        await this.operation;
        this.tables.clear();
        this.tokens.clear();
        await this.persistence?.close?.();
        this.db.destroy();
    }

    private enqueue<Result>(action: () => Promise<Result>): Promise<Result> {
        const result = this.operation.then(action);
        this.operation = result.then(() => undefined, () => undefined);
        return result;
    }

    private async load(): Promise<void> {
        const snapshot = await this.persistence?.load();
        if (snapshot === undefined) {
            await this.persistence?.save(this.snapshot());
            return;
        }
        if (snapshot.version !== 1) {
            throw new Error('Unsupported in-memory DynamoDB persistence format');
        }
        this.tables.clear();
        for (const persistedTable of snapshot.tables) {
            const table: MemoryTable = {
                description: ValueUtils.clone(persistedTable.description),
                items: new Map()
            };
            for (const persistedItem of persistedTable.items) {
                const item = QuerySerializer.parseItem<AttributeMap, unknown>(persistedItem);
                table.items.set(this.key(table, item), item);
            }
            this.tables.set(table.description.TableName!, table);
        }
    }

    private snapshot(): MemorySnapshot {
        return {
            version: 1,
            tables: Array.from(this.tables.values(), (table) => ({
                description: ValueUtils.clone(table.description),
                items: Array.from(table.items.values(), (item) => QuerySerializer.serialiseMap(item))
            }))
        };
    }

    private mutates(command: MemoryCommand): boolean {
        return command instanceof CreateTableCommand
            || command instanceof DeleteTableCommand
            || command instanceof PutItemCommand
            || command instanceof UpdateItemCommand
            || command instanceof DeleteItemCommand
            || command instanceof BatchWriteItemCommand
            || command instanceof TransactWriteItemsCommand;
    }

    private table(name: string | undefined): MemoryTable {
        const table = name === undefined ? undefined : this.tables.get(name);
        if (table === undefined) {
            throw new ResourceNotFoundException({message: `Table not found: ${name}`, $metadata: {}});
        }
        return table;
    }

    private key(table: MemoryTable, item: Document, exact = false): string {
        const schema = table.description.KeySchema || [];
        if (exact && Object.keys(item).length !== schema.length) {
            validation('The provided key does not match the table schema');
        }
        return JSON.stringify(schema.map((element) => {
            const name = element.AttributeName!;
            const value = item[name];
            const definition = (table.description.AttributeDefinitions || [])
                .find((entry) => entry.AttributeName === name);
            const type = typeof value === 'string'
                ? 'S'
                : typeof value === 'number'
                    ? 'N'
                    : value instanceof Uint8Array
                        ? 'B'
                        : null;
            if (
                !Object.prototype.hasOwnProperty.call(item, name)
                || type === null
                || definition === undefined
                || type !== definition.AttributeType
                || (typeof value === 'number' && !Number.isFinite(value))
                || value === ''
                || (value instanceof Uint8Array && value.length === 0)
            ) {
                validation(`Invalid key attribute: ${name}`);
            }
            return [
                name,
                type,
                value instanceof Uint8Array ? Array.from(value) : value
            ];
        }));
    }

    private matches(expression: string | undefined, item: Document, input: QueryCommandInput): boolean {
        return expression === undefined || new MemoryExpression(
            expression,
            item,
            input.ExpressionAttributeNames || {},
            input.ExpressionAttributeValues || {}
        ).evaluate();
    }

    private condition(input: ConditionCheck | WriteInput, item: Document | undefined): void {
        if (!this.matches(input.ConditionExpression, item === undefined ? {} : item, input)) {
            throw new ConditionalCheckFailedException({
                message: 'The conditional request failed',
                $metadata: {},
                Item: input.ReturnValuesOnConditionCheckFailure === 'ALL_OLD' && item !== undefined
                    ? QuerySerializer.serialiseMap(item)
                    : undefined
            });
        }
    }

    private metadata(input: {TableName?: string; ReturnConsumedCapacity?: string}): object {
        if (input.ReturnConsumedCapacity === undefined || input.ReturnConsumedCapacity === 'NONE') {
            return {};
        }
        return {ConsumedCapacity: {TableName: input.TableName, CapacityUnits: 1}};
    }

    private itemCollectionMetrics(input: WriteInput, table: MemoryTable, item: Document): object {
        if (input.ReturnItemCollectionMetrics !== 'SIZE' || (table.description.LocalSecondaryIndexes || []).length === 0) {
            return {};
        }
        const partition = (table.description.KeySchema || []).find((key) => key.KeyType === 'HASH');
        if (partition === undefined || item[partition.AttributeName!] === undefined) {
            return {};
        }
        return {ItemCollectionMetrics: [{
            ItemCollectionKey: QuerySerializer.serialiseMap({[partition.AttributeName!]: item[partition.AttributeName!]}),
            SizeEstimateRangeGB: [0, 0]
        }]};
    }

    private project(item: Document, expression: string | undefined, names: Record<string, string> | undefined): Document {
        if (expression === undefined) {
            return item;
        }
        const attributes = expression.split(',').map((name) => names?.[name.trim()]);
        if (attributes.some((attribute) => attribute === undefined)) {
            validation('Unsupported in-memory projection');
        }
        return Object.fromEntries(attributes
            .filter((attribute): attribute is string => attribute !== undefined && Object.prototype.hasOwnProperty.call(item, attribute))
            .map((attribute) => [attribute, item[attribute]]));
    }

    private write(kind: 'put' | 'update' | 'delete' | 'check', input: WriteInput): object {
        const table = this.table(input.TableName);
        const selector = QuerySerializer.parseItem<AttributeMap, unknown>(
            kind === 'put' ? input.Item! : input.Key!
        );
        const key = this.key(table, selector, kind !== 'put');
        const previous = table.items.get(key);
        this.condition(input, previous);
        if (kind === 'check') {
            return {};
        }
        let next = ValueUtils.clone(previous === undefined ? selector : previous);
        if (kind === 'put') {
            next = selector;
        } else if (kind === 'update') {
            this.update(next, input, table.description.KeySchema || []);
        }
        if (kind === 'delete') {
            table.items.delete(key);
        } else {
            table.items.set(key, ValueUtils.clone(next));
        }
        const returned = input.ReturnValues === 'ALL_OLD'
            ? previous
            : input.ReturnValues === 'ALL_NEW'
                ? next
                : undefined;
        return {
            ...(returned === undefined ? {} : {Attributes: QuerySerializer.serialiseMap(returned)}),
            ...this.metadata(input),
            ...this.itemCollectionMetrics(input, table, next)
        };
    }

    private update(item: Document, input: WriteInput, keys: KeySchemaElement[]): void {
        const expression = input.UpdateExpression || '';
        const groups = Array.from(expression.matchAll(
            /\b(SET|REMOVE|ADD|DELETE)\s+(.+?)(?=\s+(?:SET|REMOVE|ADD|DELETE)\s|$)/g
        ));
        if (groups.length === 0 || groups.map((group) => group[0]).join(' ') !== expression) {
            validation(`Unsupported in-memory update: ${expression}`);
        }
        for (const group of groups) {
            for (const clause of group[2].split(', ')) {
                const match = /^(#[\w.-]+)(?: = (:[\w.-]+)| (:[\w.-]+))?$/.exec(clause);
                if (match === null) {
                    validation(`Unsupported in-memory update clause: ${clause}`);
                }
                const name = (input.ExpressionAttributeNames || {})[match[1]];
                if (name === undefined || keys.some((key) => key.AttributeName === name)) {
                    validation(`Invalid update attribute: ${name}`);
                }
                if (group[1] === 'REMOVE') {
                    delete item[name];
                    continue;
                }
                const encoded = (input.ExpressionAttributeValues || {})[match[2] || match[3]];
                if (encoded === undefined) {
                    validation(`Missing update value for ${name}`);
                }
                const value: unknown = QuerySerializer.parseField(encoded);
                const previous = item[name];
                if (group[1] === 'SET') {
                    Object.defineProperty(item, name, {
                        value: value,
                        enumerable: true,
                        configurable: true,
                        writable: true
                    });
                } else if (
                    group[1] === 'ADD'
                    && typeof value === 'number'
                    && (previous === undefined || typeof previous === 'number')
                ) {
                    const previousNumber = typeof previous === 'number' ? previous : 0;
                    item[name] = previousNumber + value;
                } else if (
                    value instanceof Set
                    && (previous === undefined || previous instanceof Set)
                ) {
                    const valueEntries: unknown[] = Array.from(value);
                    const entries: unknown[] = previous instanceof Set ? Array.from(previous) : [];
                    if (previous !== undefined) {
                        const previousType = Object.keys(QuerySerializer.serialiseItem(previous))[0];
                        const valueType = Object.keys(encoded)[0];
                        if (previousType !== valueType) {
                            validation(`Set types must match for ${name}`);
                        }
                    }
                    if (group[1] === 'ADD') {
                        for (const entry of valueEntries) {
                            if (!entries.some((existing) => ValueUtils.equals(existing, entry))) {
                                entries.push(entry);
                            }
                        }
                        item[name] = new Set(entries);
                    } else {
                        const remaining = entries.filter(
                            (entry) => !valueEntries.some((removed) => ValueUtils.equals(entry, removed))
                        );
                        if (remaining.length === 0) {
                            delete item[name];
                        } else {
                            item[name] = new Set(remaining);
                        }
                    }
                } else {
                    validation(`Invalid ${group[1]} value for ${name}`);
                }
            }
        }
    }

    // Query and scan execution.
    private read(input: QueryCommandInput | ScanCommandInput, query: boolean): object {
        const table = this.table(input.TableName);
        const queryInput = input as QueryCommandInput;
        let schema = table.description.KeySchema || [];
        let projectedAttributes: Set<string> | null = null;
        let globalIndex = false;
        const indexRequest = input.IndexName !== undefined;
        if (input.IndexName !== undefined) {
            const global = (table.description.GlobalSecondaryIndexes || [])
                .find((index) => index.IndexName === input.IndexName);
            const local = (table.description.LocalSecondaryIndexes || [])
                .find((index) => index.IndexName === input.IndexName);
            const index = global === undefined ? local : global;
            if (index === undefined || (global !== undefined && input.ConsistentRead === true)) {
                validation(`Invalid index request: ${input.IndexName}`);
            }
            if (index.Projection === undefined) {
                validation('In-memory index does not define a projection');
            }
            schema = index.KeySchema || [];
            globalIndex = global !== undefined;
            if (index.Projection.ProjectionType !== 'ALL') {
                projectedAttributes = new Set(
                    [...(table.description.KeySchema || []), ...schema]
                        .map((key) => key.AttributeName!)
                );
                for (const attribute of index.Projection.NonKeyAttributes || []) {
                    projectedAttributes.add(attribute);
                }
            }
        }
        if (query && queryInput.KeyConditionExpression === undefined) {
            validation('Query requires a key condition');
        }
        this.matches(query ? queryInput.KeyConditionExpression : undefined, {}, input as QueryCommandInput);
        this.matches(input.FilterExpression, {}, input);
        if (query) {
            const aliases = (queryInput.KeyConditionExpression || '').match(/#[\w.-]+/g) || [];
            const names = input.ExpressionAttributeNames || {};
            const partition = schema.find((key) => key.KeyType === 'HASH')!;
            const partitionAliases = aliases.filter((alias) => names[alias] === partition.AttributeName);
            if (
                partitionAliases.length !== 1
                || !(queryInput.KeyConditionExpression || '').includes(`${partitionAliases[0]} = :`)
                || aliases.some((alias) => !schema.some((key) => key.AttributeName === names[alias]))
            ) {
                validation('Query requires partition-key equality and only declared key attributes');
            }
            const filterAliases = (input.FilterExpression || '').match(/#[\w.-]+/g) || [];
            if (filterAliases.some((alias) => schema.some((key) => key.AttributeName === names[alias]))) {
                validation('Query filters cannot reference key attributes');
            }
            if (indexRequest && projectedAttributes !== null
                && filterAliases.some((alias) => !projectedAttributes!.has(names[alias]))) {
                validation('Secondary index filters require projected attributes');
            }
        }
        if (input.ProjectionExpression !== undefined && input.Select !== undefined && input.Select !== 'SPECIFIC_ATTRIBUTES') {
            validation('ProjectionExpression requires SPECIFIC_ATTRIBUTES when Select is provided');
        }
        if (input.Select === 'SPECIFIC_ATTRIBUTES' && input.ProjectionExpression === undefined) {
            validation('SPECIFIC_ATTRIBUTES requires ProjectionExpression');
        }
        if (input.Select === 'ALL_PROJECTED_ATTRIBUTES' && !indexRequest) {
            validation('ALL_PROJECTED_ATTRIBUTES requires an index');
        }
        if (input.Select === 'ALL_ATTRIBUTES' && globalIndex && projectedAttributes !== null) {
            validation('Global secondary index cannot return all table attributes');
        }
        const requestedAttributes = input.ProjectionExpression === undefined
            ? null
            : input.ProjectionExpression.split(',')
                .map((name) => (input.ExpressionAttributeNames || {})[name.trim()]);
        if (requestedAttributes !== null && requestedAttributes.some((name) => name === undefined)) {
            validation('Unsupported in-memory projection');
        }
        if (globalIndex && projectedAttributes !== null && requestedAttributes !== null
            && requestedAttributes.some((attribute) => !projectedAttributes!.has(attribute))) {
            validation('Global secondary index query requested a non-projected attribute');
        }
        let items = Array.from(table.items.values()).filter(
            (item) => schema.every((key) => item[key.AttributeName!] !== undefined)
                && (!query || this.matches(queryInput.KeyConditionExpression, item, queryInput))
        );
        if (query) {
            const sort = schema.find((key) => key.KeyType === 'RANGE');
            if (sort !== undefined) {
                items.sort((left, right) => compare(left[sort.AttributeName!], right[sort.AttributeName!]) || 0);
            }
            if (queryInput.ScanIndexForward === false) {
                items.reverse();
            }
        }
        if (!query) {
            const scan = input as ScanCommandInput;
            if ((scan.Segment === undefined) !== (scan.TotalSegments === undefined)
                || (scan.TotalSegments !== undefined && (!Number.isInteger(scan.TotalSegments) || scan.TotalSegments < 1
                    || !Number.isInteger(scan.Segment) || scan.Segment! < 0 || scan.Segment! >= scan.TotalSegments))) {
                validation('Invalid parallel scan segment');
            }
            if (scan.Segment !== undefined) {
                items = items.filter((item) => {
                    const key = this.key(table, item);
                    let hash = 0;
                    for (let index = 0; index < key.length; index++) hash = (hash * 31 + key.charCodeAt(index)) >>> 0;
                    return hash % scan.TotalSegments! === scan.Segment;
                });
            }
        }
        if (input.ExclusiveStartKey !== undefined) {
            const cursorKey = this.key(table, QuerySerializer.parseItem(input.ExclusiveStartKey));
            const position = items.findIndex((item) => this.key(table, item) === cursorKey);
            if (position === -1) {
                validation('In-memory cursor must identify an existing matching record');
            }
            items = items.slice(position + 1);
        }
        const limit = input.Limit === undefined ? items.length : input.Limit;
        if (input.Limit !== undefined && (!Number.isInteger(limit) || limit <= 0)) {
            validation('Limit must be a positive integer');
        }
        const evaluated = items.slice(0, limit);
        const filtered = evaluated.filter((item) => this.matches(input.FilterExpression, item, input));
        let lastKey: AttributeMap | undefined;
        if (evaluated.length < items.length && evaluated.length > 0) {
            const last = evaluated[evaluated.length - 1];
            lastKey = QuerySerializer.serialiseMap(
                Object.fromEntries(
                    [...(table.description.KeySchema || []), ...schema]
                        .map((key) => [key.AttributeName!, last[key.AttributeName!]])
                )
            );
        }
        return {
            ...this.metadata(input),
            Items: input.Select === 'COUNT'
                ? undefined
                : filtered.map((item) => {
                    const attributes = requestedAttributes === null
                        ? input.Select === 'ALL_ATTRIBUTES'
                            ? null
                            : projectedAttributes === null ? null : Array.from(projectedAttributes)
                        : requestedAttributes;
                    if (attributes === null) {
                        return QuerySerializer.serialiseMap(item);
                    }
                    return QuerySerializer.serialiseMap(
                        Object.fromEntries(
                            attributes
                                .filter((name) => Object.prototype.hasOwnProperty.call(item, name))
                                .map((name) => [name, item[name]])
                        )
                    );
                }),
            Count: filtered.length,
            ScannedCount: evaluated.length,
            LastEvaluatedKey: lastKey
        };
    }

    // Transactions validate and apply all writes against an isolated snapshot.
    private transaction(input: TransactWriteItemsCommandInput): object {
        const writes = input.TransactItems || [];
        if (writes.length === 0 || writes.length > 100) {
            validation('Transactions require between 1 and 100 operations');
        }
        const token = input.ClientRequestToken;
        if (token !== undefined) {
            if (token.length < 1 || token.length > 36) {
                validation('Invalid transaction request token');
            }
            const previous = this.tokens.get(token);
            if (previous !== undefined && previous.expires > Date.now()) {
                if (!ValueUtils.equals(previous.input, input)) {
                    throw new DynamoDBServiceException({
                        name: 'IdempotentParameterMismatchException',
                        message: 'Request token reused with different input',
                        $fault: 'client',
                        $metadata: {}
                    });
                }
                return {};
            }
        }
        const snapshot = ValueUtils.clone(this.tables);
        const targets = new Set<string>();
        let position = 0;
        try {
            for (const entry of writes) {
                const write = entry.Put || entry.Update || entry.Delete || entry.ConditionCheck;
                if (write === undefined || Object.keys(entry).length !== 1) {
                    validation('Invalid transaction item');
                }
                const kind = entry.Put !== undefined
                    ? 'put'
                    : entry.Update !== undefined
                        ? 'update'
                        : entry.Delete !== undefined
                            ? 'delete'
                            : 'check';
                const selector = QuerySerializer.parseItem(
                    entry.Put !== undefined ? entry.Put.Item! : (write as ConditionCheck).Key!
                );
                const target = JSON.stringify([
                    write.TableName,
                    this.key(this.table(write.TableName), selector, kind !== 'put')
                ]);
                if (targets.has(target)) {
                    validation('Transaction cannot target the same item twice');
                }
                targets.add(target);
                this.write(kind, write);
                position++;
            }
        } catch (error) {
            this.tables = snapshot;
            if (error instanceof ConditionalCheckFailedException) {
                throw new TransactionCanceledException({
                    message: 'Transaction cancelled',
                    $metadata: {},
                    CancellationReasons: writes.map((entry, index) => index === position
                        ? {Code: 'ConditionalCheckFailed', Message: error.message, Item: error.Item}
                        : {Code: 'None'})
                });
            }
            throw error;
        }
        if (token !== undefined) {
            this.tokens.set(token, {input: ValueUtils.clone(input), expires: Date.now() + 600000});
        }
        return {};
    }

    // Translate each supported SDK command into an in-memory operation.
    private execute(command: MemoryCommand): object {
        const commandName = command.constructor.name;
        if (command instanceof CreateTableCommand) {
            const input = ValueUtils.clone(command.input);
            const name = input.TableName;
            const keys = input.KeySchema || [];
            const validKeys = (schema: KeySchemaElement[]) =>
                schema.filter((key) => key.KeyType === 'HASH').length === 1
                && schema.filter((key) => key.KeyType === 'RANGE').length <= 1
                && schema.length >= 1
                && schema.length <= 2
                && new Set(schema.map((key) => key.AttributeName)).size === schema.length
                && schema.every((key) => (key.KeyType === 'HASH' || key.KeyType === 'RANGE')
                    && (input.AttributeDefinitions || []).some((attribute) =>
                        attribute.AttributeName === key.AttributeName
                        && ['S', 'N', 'B'].includes(attribute.AttributeType!)));
            if (!name || !validKeys(keys)) {
                validation('Table requires a name and valid key definitions');
            }
            const indexes = [...(input.GlobalSecondaryIndexes || []), ...(input.LocalSecondaryIndexes || [])];
            const validProjection = (index: typeof indexes[number]): boolean => {
                const projection = index.Projection;
                if (projection === undefined || !['ALL', 'KEYS_ONLY', 'INCLUDE'].includes(projection.ProjectionType!)) {
                    return false;
                }
                if (projection.ProjectionType !== 'INCLUDE') {
                    return projection.NonKeyAttributes === undefined || projection.NonKeyAttributes.length === 0;
                }
                const attributes = projection.NonKeyAttributes || [];
                const projectedKeys = new Set(
                    [...keys, ...(index.KeySchema || [])].map((key) => key.AttributeName)
                );
                return attributes.length > 0 && attributes.length <= 20
                    && new Set(attributes).size === attributes.length
                    && attributes.every((attribute) => attribute.length > 0 && !projectedKeys.has(attribute));
            };
            if (
                new Set(indexes.map((index) => index.IndexName)).size !== indexes.length
                || indexes.some((index) => !index.IndexName
                    || !validKeys(index.KeySchema || [])
                    || !validProjection(index))
            ) {
                validation('In-memory indexes require unique names, valid keys and projections');
            }
            const projectedAttributeCount = indexes.reduce(
                (total, index) => total + (index.Projection?.NonKeyAttributes || []).length,
                0
            );
            if (projectedAttributeCount > 100) {
                validation('In-memory indexes project more than 100 non-key attributes');
            }
            const partition = keys.find((key) => key.KeyType === 'HASH')!;
            if ((input.LocalSecondaryIndexes || []).some((index) =>
                keys.length !== 2
                || (index.KeySchema || []).length !== 2
                || !(index.KeySchema || []).some((key) =>
                    key.KeyType === 'HASH' && key.AttributeName === partition.AttributeName))) {
                validation('Local indexes require the table partition key and a sort key');
            }
            if (this.tables.has(name)) {
                throw new DynamoDBServiceException({
                    name: 'ResourceInUseException',
                    message: `Table already exists: ${name}`,
                    $fault: 'client',
                    $metadata: {}
                });
            }
            const description: TableDescription = {...input, TableStatus: 'ACTIVE'};
            this.tables.set(name, {description: description, items: new Map()});
            return {TableDescription: description};
        }
        if (command instanceof ListTablesCommand) {
            return {TableNames: Array.from(this.tables.keys()).sort()};
        }
        if (command instanceof DescribeTableCommand || command instanceof DeleteTableCommand) {
            const table = this.table(command.input.TableName);
            if (command instanceof DeleteTableCommand) {
                this.tables.delete(command.input.TableName!);
                return {TableDescription: table.description};
            }
            return {Table: {...table.description, ItemCount: table.items.size}};
        }
        if (command instanceof GetItemCommand) {
            const table = this.table(command.input.TableName);
            const item = table.items.get(
                this.key(table, QuerySerializer.parseItem(command.input.Key!), true)
            );
            return {
                ...this.metadata(command.input),
                ...(item === undefined ? {} : {Item: QuerySerializer.serialiseMap(this.project(
                    item,
                    command.input.ProjectionExpression,
                    command.input.ExpressionAttributeNames
                ))})
            };
        }
        if (command instanceof PutItemCommand) {
            return this.write('put', command.input);
        }
        if (command instanceof UpdateItemCommand) {
            return this.write('update', command.input);
        }
        if (command instanceof DeleteItemCommand) {
            return this.write('delete', command.input);
        }
        if (command instanceof QueryCommand) {
            return this.read(command.input, true);
        }
        if (command instanceof ScanCommand) {
            return this.read(command.input, false);
        }
        if (command instanceof TransactWriteItemsCommand) {
            return this.transaction(command.input);
        }
        if (command instanceof BatchWriteItemCommand) {
            for (const [name, writes] of Object.entries(command.input.RequestItems || {})) {
                for (const write of writes) {
                    if (write.PutRequest !== undefined) {
                        this.write('put', {TableName: name, Item: write.PutRequest.Item});
                    } else if (write.DeleteRequest !== undefined) {
                        this.write('delete', {TableName: name, Key: write.DeleteRequest.Key});
                    } else {
                        validation('Unsupported batch write');
                    }
                }
            }
            return {
                ...this.metadata({ReturnConsumedCapacity: command.input.ReturnConsumedCapacity}),
                UnprocessedItems: {}
            };
        }
        if (command instanceof BatchGetItemCommand) {
            const responses: Record<string, AttributeMap[]> = {};
            for (const [name, request] of Object.entries(command.input.RequestItems || {})) {
                const table = this.table(name);
                responses[name] = (request.Keys || []).flatMap((key) => {
                    const item = table.items.get(
                        this.key(table, QuerySerializer.parseItem(key), true)
                    );
                    return item === undefined ? [] : [QuerySerializer.serialiseMap(this.project(
                        item,
                        request.ProjectionExpression,
                        request.ExpressionAttributeNames
                    ))];
                });
            }
            return {
                ...this.metadata({ReturnConsumedCapacity: command.input.ReturnConsumedCapacity}),
                Responses: responses,
                UnprocessedKeys: {}
            };
        }
        throw new Error(`Unsupported in-memory DynamoDB command: ${commandName}`);
    }
}

class FilePersistence implements MemoryPersistence {
    constructor(private readonly path: string) {}

    async load(): Promise<MemorySnapshot | undefined> {
        const fileSystem = await nodeFileSystem();
        try {
            return JSON.parse(await fileSystem.readFile(this.path, 'utf8'), reviveBinary) as MemorySnapshot;
        } catch (error) {
            if (isMissingFile(error)) {
                return undefined;
            }
            throw error;
        }
    }

    async save(snapshot: MemorySnapshot): Promise<void> {
        const fileSystem = await nodeFileSystem();
        await fileSystem.mkdir(directoryOf(this.path), {recursive: true});
        const temporaryPath = `${this.path}.tmp`;
        await fileSystem.writeFile(temporaryPath, JSON.stringify(snapshot, replaceBinary), 'utf8');
        await fileSystem.rename(temporaryPath, this.path);
    }
}

class IndexedDBPersistence implements MemoryPersistence {
    private database?: Promise<IDBDatabase>;

    constructor(private readonly name: string) {}

    async load(): Promise<MemorySnapshot | undefined> {
        const database = await this.open();
        return this.request(database.transaction('fluentful-orm', 'readonly').objectStore('fluentful-orm').get('state'));
    }

    async save(snapshot: MemorySnapshot): Promise<void> {
        await this.transaction(await this.open(), snapshot);
    }

    async close(): Promise<void> {
        (await this.database)?.close();
    }

    private open(): Promise<IDBDatabase> {
        if (this.database === undefined) {
            if (typeof indexedDB === 'undefined') {
                throw new Error('IndexedDB is not available in this environment');
            }
            this.database = new Promise((resolve, reject) => {
                const request = indexedDB.open(this.name, 1);
                request.onupgradeneeded = () => {
                    request.result.createObjectStore('fluentful-orm');
                };
                request.onsuccess = () => resolve(request.result);
                request.onerror = () => reject(request.error);
            });
        }
        return this.database;
    }

    private request(request: IDBRequest<MemorySnapshot | undefined>): Promise<MemorySnapshot | undefined> {
        return new Promise((resolve, reject) => {
            request.onsuccess = () => resolve(request.result);
            request.onerror = () => reject(request.error);
        });
    }

    private transaction(database: IDBDatabase, snapshot: MemorySnapshot): Promise<void> {
        return new Promise((resolve, reject) => {
            const transaction = database.transaction('fluentful-orm', 'readwrite');
            transaction.objectStore('fluentful-orm').put(snapshot, 'state');
            transaction.oncomplete = () => resolve();
            transaction.onerror = () => reject(transaction.error);
            transaction.onabort = () => reject(transaction.error);
        });
    }
}

function replaceBinary(_key: string, value: unknown): unknown {
    return value instanceof Uint8Array ? {fluentfulBinary: Array.from(value)} : value;
}

function reviveBinary(_key: string, value: unknown): unknown {
    if (
        value !== null
        && typeof value === 'object'
        && Object.keys(value).length === 1
        && Array.isArray((value as {fluentfulBinary?: unknown}).fluentfulBinary)
    ) {
        return new Uint8Array((value as {fluentfulBinary: number[]}).fluentfulBinary);
    }
    return value;
}

function isMissingFile(error: unknown): boolean {
    return typeof error === 'object'
        && error !== null
        && (error as {code?: unknown}).code === 'ENOENT';
}

function directoryOf(path: string): string {
    const separator = Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\'));
    return separator < 0 ? '.' : path.slice(0, separator + 1);
}

async function nodeFileSystem(): Promise<typeof import('node:fs/promises')> {
    if (typeof process === 'undefined' || process.versions?.node === undefined) {
        throw new Error('File persistence is only available in Node.js');
    }
    return Function('specifier', 'return import(specifier)')('node:fs/promises') as Promise<typeof import('node:fs/promises')>;
}

/** Creates memory-backed DynamoDB-compatible engines for memory, browser, and file storage. */
export const createEngine = {
    memory(tables: InitialTables = []): InMemoryDynamoDB {
        return new InMemoryDynamoDB(tables);
    },
    indexDB(name = 'fluentful-orm', tables: InitialTables = []): InMemoryDynamoDB {
        return new InMemoryDynamoDB(tables, new IndexedDBPersistence(name));
    },
    file(path: string, tables: InitialTables = []): InMemoryDynamoDB {
        return new InMemoryDynamoDB(tables, new FilePersistence(path));
    }
};
